language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: e-commerce-api-react
  api_key:
    secure: OsQgTxWbTHVYiTFIDK55toq0x7rudeEjL13OLwBzKrVk13igL52tsKYg1r+JHuEU70svYea/flyR8OUJbPynKgAX10oU/JeNdjolIX3ZqPrR64XZYKpSxG0NLRo92rib8m2AlC3wr2xoqCBsOaYQy1FCcf2OSSaByEzo3QTpt66M9DoQ8KpNM01EPFMUn2A3gr0zFwVGHnWrF0QgJuJHQmv0vPTs78cmeXuqK2mE9qSaz6XkuWGNJyq8iduceH7jpf3+eT9cnPZRVd9lWl+5LghCKSp49Zb+ZR8Vq9+Ex3vaf3gCqzPT1nzRjreMHt2xpN23j3iAEkGk8kdMQRwusvp4/LfFG5IZhho7IQTaVlX3zGgmWSyI3B4zgaCOOP9LmJR3OXNSptYicvWs2tfs1SC4VCzaL1/AAlsfnsXHbihlJaqz3idPwuaYOVysAQ0NcFmdkiPb1/7NIMobx23ZpBwLh7DJYsl/LOUL2pmkQTam9NiMfXRWVQc2tgiyy9ofqtprkxTShxKE15CLDuFlUaAPk5NYltSWO0wMmjl7metmtGrWLPBpOMopYq2WWOsRs21i3hmz8HQj82U9sQnYDmQcJH818qxu3+SXC++cfSNykXeWsosXTYiPInsOivykAmwgSqsb0Mv24Pov7Y4FKLq1AfRvCD/MU5F1AOeAIJU=
